spring:
  application:
    name: graphql-java-tools-app
  kafka:
    consumer:
      bootstrap-servers: dev-kafka-heimdall-worker-0:9092
      group-id: group_id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      security.protocol: SASL_SSL
      sasl.mechanism: SCRAM-SHA-256
      ssl.truststore.location: /home/statarm/Downloads/truststore.jks
      ssl.truststore.password: client
      sasl.jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule
      username: "edhpipeline"
      password: "jygw3Dp98PtejS2D"
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      security.protocol: SASL_SSL
        sasl.mechanism: SCRAM-SHA-256
        ssl.truststore.location: /home/statarm/Downloads/truststore.jks
        ssl.truststore.password: client
        sasl.jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule
        username: "edhpipeline"
        password: "jygw3Dp98PtejS2D"
server:
  port: 9001
graphql:
  servlet:
    exception-handlers-enabled: true
graphiql:
  headers:
    Authorization: "Bearer 05bd9a5f3fe0408f89520946b0fe1b06"
logging:
  level:
    com:
      oembedler:
        moon:
          graphql:
            boot:
              error: debug

